language: php

php:
  - hhvm
  - 7.0
  - 5.6.4

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

script:
  - vendor/bin/phpunit

install: composer create-project webklex/postfixadm --no-interaction

notifications:
  email:
    on_success: always
    on_failure: always