language: php

php:
  - hhvm
  - 7.0
  - 5.6
  - 5.5

matrix:
  fast_finish: true
  allow_failures:
    - php: hhvm

sudo: false

install: composer install --no-interaction

notifications:
  email:
    on_success: always
    on_failure: always