<?php
/*
 * File: test.blade.php
 * Category: View
 * Author: MSG
 * Created: 03.04.17 10:09
 * Updated: -
 *
 * Description:
 *  -
 */


?>

<br />
<br />
<br />
@t('This is just a test mail and generated by postfixADM.')
<br />
@t('Go ahead and delete this mail. It is no longer required for anything else.')
<br />
<br />
<br />
----
<br />
PostfixADM - @t('the modern Mail backend')
